### ISSUE TITLE
No plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly.

### ISSUE THREAD

**Issue by kfriede** [homebridge-plugins/homebridge-roomba#46]
Getting error message "No plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly." in Homebridge logs

### Expected Behavior
No error message, and plugin loads

### Current Behavior
```
[5/8/2021, 11:05:40 AM] Loading 1 accessories...
[5/8/2021, 11:05:40 AM] No plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

### Versions
- **Homebridge**: v1.3.4
- **Node**: v14.16.1
- **Plugin**: v1.2.0 

### Configuration
```json
"accessories": [
        {
            "accessory": "Roomba2",
            "name": "Roomba2",
            "model": "e619820",
            "blid": "<REMOVED>",
            "robotpwd": "<REMOVED>",
            "ipaddress": "<REMOVED>",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "dockContactSensor": true,
            "cacheTTL": 30
        }
    ],
```

### Homebridge Log / Command Output
```
[5/8/2021, 11:05:40 AM] Loading 1 accessories...
[5/8/2021, 11:05:40 AM] No plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

**Comment by kfriede** [comment]
Solved, plugin requires the following in config (not auto-configured):
``` json
    "plugins": [
        "homebridge-roomba2"
    ],
```

**Comment by jlg89** [comment]
Updated from 1.5.3 to 2.1.0, config was wiped out. Reconfigured via GUI, using values from a backup. Now getting this "No plugin was found" error. Can't get 2.0.1 to run at all, had to revert to 1.5.3 (and reconfigure again).

Homebridge 1.9.0
UI 4.7.1.2
Node.js 22.14.0
Host OS: macOS 15.3.1

```
[3/7/2025, 8:47:35 AM] [Roomba] Child bridge process ended
[3/7/2025, 8:47:35 AM] [Roomba] Process Ended. Code: 1, Signal: null
[3/7/2025, 8:47:42 AM] [Roomba] Restarting child bridge...
[3/7/2025, 8:47:42 AM] [Roomba] Restarting Process...
[3/7/2025, 8:47:44 AM] [Roomba] Launched child bridge with PID 49180
[3/7/2025, 8:47:45 AM] Registering platform '@homebridge-plugins/homebridge-roomba.Roomba'
[3/7/2025, 8:47:45 AM] [Roomba] Loaded @homebridge-plugins/homebridge-roomba v2.1.0 child bridge successfully
[3/7/2025, 8:47:45 AM] Loaded 0 cached accessories from cachedAccessories.0E864C5B26F3.
Error: No plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:231:15)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:167:43)
[3/7/2025, 8:47:45 AM] [Roomba] Child bridge process ended
[3/7/2025, 8:47:45 AM] [Roomba] Process Ended. Code: 1, Signal: null
[3/7/2025, 8:47:52 AM] [Roomba] Restarting Process...
[3/7/2025, 8:47:54 AM] [Roomba] Launched child bridge with PID 49193
[3/7/2025, 8:47:56 AM] [Roomba] Loaded @homebridge-plugins/homebridge-roomba v2.1.0 child bridge successfully
[3/7/2025, 8:47:56 AM] [Roomba] Child bridge process ended
[3/7/2025, 8:47:56 AM] [Roomba] Process Ended. Code: 1, Signal: null
[3/7/2025, 8:48:03 AM] [Roomba] Restarting Process...
[3/7/2025, 8:48:05 AM] [Roomba] Launched child bridge with PID 49206
[3/7/2025, 8:48:06 AM] [Roomba] Loaded @homebridge-plugins/homebridge-roomba v2.1.0 child bridge successfully
[3/7/2025, 8:48:06 AM] [Roomba] Child bridge process ended
[3/7/2025, 8:48:06 AM] [Roomba] Process Ended. Code: 1, Signal: null
[3/7/2025, 8:48:13 AM] [Roomba] Restarting Process...
[3/7/2025, 8:48:15 AM] [Roomba] Launched child bridge with PID 49219
[3/7/2025, 8:48:16 AM] [Roomba] Loaded @homebridge-plugins/homebridge-roomba v2.1.0 child bridge successfully
[3/7/2025, 8:48:16 AM] [Roomba] Child bridge process ended
[3/7/2025, 8:48:16 AM] [Roomba] Process Ended. Code: 1, Signal: null
```

**Comment by frizzma** [comment]
Same issue here with a j7+.  Upgraded from 1.5.3 to 2.1.0 and now get the error "No plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly."

Tried changing the accessory name to "Roomba" in config.json since the documentation [here](https://github.com/homebridge-plugins/homebridge-roomba?tab=readme-ov-file#manual-configuration) and [here](https://github.com/homebridge-plugins/homebridge-roomba/wiki/#manual-configuration) state two different values.  Same error, it just says it can't find the plugin for accessory "Roomba" in config.json.

Tried adding the `plugins: []` entry in config.json described above, but that breaks all my other bridges.  It looks like 1.5.3 doesn't add a `plugins` entry either, there's only the Roomba2 accessory in config.json.

Not sure if it matters, but I'm running the "scoped" plugin... so the plugin is in `node_modules/@homebridge-plugins/homebridge-roomba2` all the documentation seems to be geared towards the standard non-scoped plugin.  Also, for the j7+ it's not possible to get the robot pw with `npm run roomba:getpassword <IP ADDRESS>` we have to use the dorita980 tool `getPasswordCloud.js`... all of this to say, maybe it's just a connection issue that isn't handled well so the accessory just fails to initialize?

Anyway, I uninstalled and deleted the config then reinstalled 1.5.3 and it's working again.

```
[3/8/2025, 10:41:15 AM] Loaded plugin: @homebridge-plugins/homebridge-roomba@2.1.0
[3/8/2025, 10:41:15 AM] Registering platform '@homebridge-plugins/homebridge-roomba.Roomba'
...
[3/8/2025, 10:41:15 AM] Loading 1 accessories...
[3/8/2025, 10:41:15 AM] No plugin was found for the accessory "Roomba2" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

vs. 1.5.3:
```

[3/8/2025, 11:02:41 AM] Loaded plugin: @homebridge-plugins/homebridge-roomba@1.5.3
[3/8/2025, 11:02:41 AM] Plugin '@homebridge-plugins/homebridge-roomba' tried to register with an incorrect plugin identifier: 'homebridge-roomba'. Please report this to the developer!
[3/8/2025, 11:02:41 AM] Registering accessory '@homebridge-plugins/homebridge-roomba.Roomba2'
...
[3/8/2025, 11:02:41 AM] Loading 1 accessories...
[3/8/2025, 11:02:41 AM] [Roomba] Initializing Roomba2 accessory...
```

**Comment by jlg89** [comment]
Yeah, the `nom run roomba:getpassword` didn't work for me either under 2.0.1.

**Comment by bwp91** [comment]
This is the same 1.x-accessory → 2.x-platform config migration covered in #163 — the leftover `"accessory": "Roomba2"` entry needs removing from `config.json`. Full steps are there. Closing as a duplicate; comment on #163 if the fix doesn't work for you.
